server:
  port: 8771
eureka:
#  instance:
#    hostname: ${spring.application.name}
#    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-client-service